# Joining and Splitting using Numpy

In [2]:
import numpy as np

arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [4]:
n_arr=np.hsplit(arr,2)
print(n_arr[1])

[4 5 6]


In [7]:
arr1=np.vstack((n_arr[0],n_arr[1]))
print(arr1)

[[1 2 3]
 [4 5 6]]


In [8]:
an=np.array([[1,2,3],[4,5,6],[7,8,9],[3,2,1]])
print(an)
print(an.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 2 1]]
(4, 3)


In [14]:
ua=np.vsplit(an,2)

print(ua[0])
print()
print(ua[1])

[[1 2 3]
 [4 5 6]]

[[7 8 9]
 [3 2 1]]


In [15]:
ua=np.hsplit(an,3)

print(ua[0].reshape(-1))
print()
print(ua[1])
print()
print(ua[2])

[1 4 7 3]

[[2]
 [5]
 [8]
 [2]]

[[3]
 [6]
 [9]
 [1]]


In [23]:
## index value will be printed
arr2=np.array([1,2,3,4,5,5,6,6,7,7,7,8,8])

x=np.where(arr2==5)
print(x[0])



[4 5]


In [25]:
## Index of the even values in the array

arr2=np.array([1,2,3,4,5,5,6,6,7,7,7,8,8])

x=np.where(arr2%2==0)
print(x[0])

[ 1  3  6  7 11 12]


# Search Sorted
There is a method called searchsorted() which performs a binary search in the array, and returns the index 
where the specified value would be inserted to maintain the search order.


In [29]:
arr3=np.array([1,2,3,4,5,6])
y=np.searchsorted(arr3,10)
print(y)

6


In [30]:
arr4=np.array([1,4,6])
y=np.searchsorted(arr3,(5,2,10))
print(y)

[4 1 6]


# Sorting Arrays
Sorting means putting elements in a ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [33]:
arr5=np.sort(arr4)

print(arr5)

[1 4 6]


In [34]:
arr6=np.array(["fox","cat","ant","box","boy"])

arr7=np.sort(arr6)

print(arr7)

['ant' 'box' 'boy' 'cat' 'fox']


In [36]:
an1=np.array([[1,21,3],[4,15,6],[17,8,9],[31,12,11]])

ab12=np.sort(an1)

print(an1)

[[ 1 21  3]
 [ 4 15  6]
 [17  8  9]
 [31 12 11]]


# Filtering Arrays
Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, 
if the value at that index is False that element is excluded from the filtered array.

In [37]:
ar12=np.array([12,23,45,67])
f_a=[True,False,True,False]

f_ar12=ar12[f_a]

print(f_ar12)

[12 45]


In [38]:
ff=ar12>=23

ff_ar12=ar12[ff]

print(ff_ar12)

[23 45 67]
