## Generate Random Number using Numpy

### int value 

In [1]:
import numpy as np

In [5]:
x=np.random.randint(100)
print(x)

47


In [8]:
y1=np.random.randint(2,size=(3,3))
print(y1)

[[1 0 0]
 [1 1 0]
 [1 1 1]]


In [9]:
y2=np.random.randint(100,size=(10))
print(y2)

[38 12  7 46 99  1 30 75 97 36]


### Float Value
The rand() method also allows you to specify the shape of the array.

In [10]:
z1=np.random.rand()
print(z1)

0.16852080953692983


In [12]:
z2=np.random.rand(2,2)
print(z2)

[[0.18722956 0.99980879]
 [0.10184054 0.8592495 ]]


## Generate Random Number From Array
The choice() method allows you to generate a random value based on an array of values.

The choice() method takes an array as a parameter and randomly returns one of the values.

In [17]:
a=np.random.choice([1,2,3])
print(a)

1


In [18]:
a2=np.random.choice([0,1],size=(5,5))
print(a2)

[[1 0 1 1 1]
 [0 1 0 1 0]
 [1 0 0 1 1]
 [0 1 1 1 1]
 [1 0 1 0 1]]


## Random Distribution
A random distribution is a set of random numbers that follow a certain probability density function.

### Probability Density Function: A function that describes a continuous probability. 
    i.e. probability of all values in an array.

We can generate random numbers based on defined probabilities using the choice() method of the random module.

The choice() method allows us to specify the probability for each value.

The probability is set by a number between 0 and 1, where 0 means that the value will never occur
and 1 means that the value will always occur.

In [19]:
pd1=np.random.choice([1,2,3],p=(0.5,0.5,0.0),size=(10))
print(pd1)

[1 1 1 1 2 1 2 2 1 2]


In [20]:
pd2=np.random.choice([0,1],p=(0.1,0.9),size=(4,4))
print(pd2)

[[1 1 1 1]
 [1 0 1 1]
 [1 1 1 1]
 [1 1 1 1]]


## Random Permutations of Elements
A permutation refers to an arrangement of elements. e.g. [3, 2, 1] is a permutation of [1, 2, 3] and vice-versa.

The NumPy Random module provides two methods for this: shuffle() and permutation().



### The shuffle() method makes changes to the original array.

In [21]:
s1=np.array([1,2,3,3,4,5,9])

np.random.shuffle(s1)
print(s1)

[9 4 1 3 3 2 5]


### The permutation() method returns a re-arranged array (and leaves the original array un-changed).

In [24]:
s2=np.array([12,23,34,45])

s3=np.random.permutation(s2)

print("original one==> ",*s2)
print()
print("new one==> ",*s3)

original one==>  12 23 34 45

new one==>  23 12 34 45


In [ ]:
np.